on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.11.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Build, tag, and push image to Docker Hub
        id: build-image
        run: |
          docker login -u fvlvte -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -q -t fvlvte/matemaksnawkurzeniu:latest .
          docker push fvlvte/matemaksnawkurzeniu:latest
